name: Cleanup Pull Request
run-name: Cleanup ${{ github.ref_name }}

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: read
  id-token: write

jobs:
  destroy:
    name: Pulumi Destroy
    uses: matt-fff/urlup-fe-infra/.github/workflows/cleanup-pr.yml@main
    secrets: inherit
