name: Deploy Production
run-name: Deploy ${{ github.ref_name }}

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Pulumi Deploy
    uses: matt-fff/urlup-fe-infra/.github/workflows/deploy-prod.yml@mw/reusable-workflow
