name: Deploy Pull Request
run-name: Deploy ${{ github.ref_name }}

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Pulumi Deploy
    uses: matt-fff/urlup-fe-infra/.github/workflows/deploy-pr.yml@mw/reusable-workflow
