# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Merge Checks
run-name: PR Checks for ${{ github.ref_name }}

on:
  push:
    branches:
      - trunk-merge/**
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  preview:
    runs-on: ubuntu-latest
    name: Pulumi Preview
    environment: pulumi
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Pulumi Login
        run: pulumi login --non-interactive >/dev/null 2>&1

      - name: Build Frontend
        run: |
          npm install
          pulumi env run "${ESCENV}" npm run build

      - name: Build Infrastructure
        run: pip install -r infra/requirements.txt

      - name: AWS Authentication
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-session-name: GHA-Merge-Checks
          role-to-assume: ${{ secrets.PULUMI_IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Pulumi Preview
        run: |
          cd infra
          pulumi stack select --stack "${STACK}"
          pulumi preview
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      ESCENV: codefold/urlup-fe-pr
      STACK: codefold/urlup-fe/dev
